# -*- coding: utf-8 -*-
"""confusion matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-cWJZEGG7Bh7Ottg5vhe8-uESKCUmgHR
"""

import pandas as pd

dataset = pd.read_csv('/content/rainfall.csv')

dataset

dataset=dataset.drop(['date'], axis=1)

dataset = dataset.drop(dataset.index[53])

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
dataset["weather_condition"] = encoder.fit_transform(dataset["weather_condition"])

x=dataset[["rainfall","temperature","humidity","wind_speed"]]
y=dataset["weather_condition"]

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=20)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay,classification_report

y_pred = model.predict(x_test)

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=model.classes_)

disp.plot(cmap="Blues")

from google.colab import drive
drive.mount('/content/drive')

print("Classification Report:")
print(classification_report(y_test, y_pred))

confusion_matrix(y_test, y_pred)

